import './globals.css'
    import { Inter } from 'next/font/google'
    import Link from 'next/link';

    const inter = Inter({ subsets: ['latin'] })

    export const metadata = {
      title: 'Portfolio',
      description: 'Generated by create next app',
    }

    export default function RootLayout({ children }) {
      return (
        <html lang="en" className='dark'>
          <body className={inter.className}>
            <nav className="bg-primary-50 dark:bg-primary-900 p-4">
              <div className="container mx-auto flex justify-between items-center">
                <Link href="/" className="text-xl font-bold text-primary-900 dark:text-primary-50">My Portfolio</Link>
              </div>
            </nav>
            <div className="flex flex-col min-h-screen">
              <main className="flex-1">
                {children}
              </main>
              <footer className="bg-primary-50 dark:bg-primary-900 text-center p-4">
                <p className="text-primary-700 dark:text-primary-300">
                  © {new Date().getFullYear()} My Portfolio. All rights reserved.
                </p>
              </footer>
            </div>
          </body>
        </html>
      )
    }
